max_tags_visible:
  type: integer
  default: 5
  description: "Maximum number of tags to display initially before showing the '+X more tags' toggle."

toggle_tag_style:
  type: enum
  default: "box"
  choices:
    - box
  description: "Visual style for the expand/collapse toggle button to match tag appearance"


highlighted_tags:
  type: list
  list_type: tag
  default: ""
  description: "Tags configured here will be moved to the front of topic tag lists and visually highlighted with accent styling."
