max_tags_visible:
  type: integer
  default: 5
  description: "Maximum number of regular (non-highlighted) tags to display initially. Highlighted tags are always shown and don't count toward this limit."

collapse_in_topic_view:
  type: bool
  default: true
  description: "Collapse/compact tags in the single topic view (topic header). When disabled, all tags are always shown on topic pages."

toggle_tag_style:
  type: enum
  default: "box"
  choices:
    - box
  description: "Visual style for the expand/collapse toggle button to match tag appearance"

highlighted_tags:
  type: list
  list_type: tag
  default: ""
  description: "Tags configured here will be moved to the front of topic tag lists and visually highlighted with accent styling."

highlighted_style:
  type: enum
  default: "left-border"
  choices:
    - left-border
    - outline
    - card
  description: "Choose the accent style for highlighted topics"
